name: build

on:
  push:
  pull_request:
  workflow_run:
    # Use a workflow as a trigger of scheduled builds. Forked repositories can disable scheduled builds by disabling
    # "scheduled" workflow, while maintaining ability to perform local CI builds.
    workflows:
      - scheduled
    branches:
      - main
      - test_actions
    types:
      - requested

jobs:
  Windows:
    runs-on: windows-2022
    env:
      VS_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        shell: cmd
        run: |
          git submodule update --init
          pip install conan
          libfwk_deps.bat

      - name: Build libfwk debug
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" windows\libfwk.vcxproj /p:Platform=x64 /p:Configuration=Debug'

      - name: Build test_window
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" windows\test_window.vcxproj /p:Platform=x64 /p:Configuration=Debug'

      - name: Build test_stuff
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" windows\test_stuff.vcxproj /p:Platform=x64 /p:Configuration=Debug'

      - name: Build test_geom
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" windows\test_geom.vcxproj /p:Platform=x64 /p:Configuration=Debug'

      - name: Build test_math
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" windows\test_math.vcxproj /p:Platform=x64 /p:Configuration=Debug'
        
      - name: Test stuff
        shell: cmd
        run: '"build\test_stuff-x64-Debug\test_stuff.exe"'

      - name: Test math
        shell: cmd
        run: '"build\test_math-x64-Debug\test_math.exe"'
